# Generated by Django 6.0.2 on 2026-02-04 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название звена')),
                ('node_type', models.CharField(choices=[('factory', 'Завод'), ('retail_network', 'Розничная сеть'), ('individual_entrepreneur', 'Индивидуальный предприниматель')], max_length=30, verbose_name='Тип звена')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, help_text='Задолженность в рублях', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('supplier', models.ForeignKey(blank=True, help_text='Вышестоящее звено в цепочке поставок', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='network.networknode', verbose_name='Поставщик')),
                ('products', models.ManyToManyField(blank=True, related_name='network_nodes', to='network.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Звено сети',
                'verbose_name_plural': 'Звенья сети',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['node_type'], name='network_net_node_ty_135ef6_idx'), models.Index(fields=['city'], name='network_net_city_874107_idx'), models.Index(fields=['country'], name='network_net_country_4e9322_idx')],
            },
        ),
    ]
