# Generated by Django 6.0.2 on 2026-02-05 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "model"], "verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, help_text="Подробное описание продукта", verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Цена в рублях",
                max_digits=10,
                null=True,
                verbose_name="Рекомендованная цена",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="city",
            field=models.CharField(help_text="Город, где находится звено сети", max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="country",
            field=models.CharField(default="Россия", max_length=100, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи (заполняется автоматически)",
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Задолженность в рублях с точностью до копеек",
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="email",
            field=models.EmailField(
                help_text="Контактный email для связи", max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="house_number",
            field=models.CharField(
                help_text="Номер дома, включая корпус/строение", max_length=20, verbose_name="Номер дома"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="name",
            field=models.CharField(
                help_text="Официальное название компании или ИП", max_length=255, verbose_name="Название звена"
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Контактный телефон",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: '+79991234567'. До 15 цифр.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Продукты, которые доступны у данного звена",
                related_name="network_nodes",
                to="network.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AlterField(
            model_name="networknode",
            name="street",
            field=models.CharField(help_text="Название улицы", max_length=100, verbose_name="Улица"),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(help_text="Модель или артикул продукта", max_length=255, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Полное название продукта", max_length=255, verbose_name="Название продукта"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(
                help_text="Дата, когда продукт стал доступен для покупки", verbose_name="Дата выхода на рынок"
            ),
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(fields=["created_at"], name="network_net_created_556489_idx"),
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(fields=["supplier"], name="network_net_supplie_bbe473_idx"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(fields=("name", "model"), name="unique_product_name_model"),
        ),
    ]
