# Generated by Django 6.0.2 on 2026-02-06 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_product_options_product_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Отдел, в котором работает сотрудник",
                        max_length=100,
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, help_text="Должность сотрудника", max_length=100, verbose_name="Должность"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Рабочий телефон")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Определяет, имеет ли сотрудник доступ к системе",
                        verbose_name="Активный сотрудник",
                    ),
                ),
                ("hire_date", models.DateField(auto_now_add=True, verbose_name="Дата приема на работу")),
                ("last_login_date", models.DateTimeField(blank=True, null=True, verbose_name="Дата последнего входа")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
    ]
